const inventory = [
  {
    "product_id": "HEA-0001",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Shaquille O'Neal",
    "description": "Color 8x10 Of Shaq mounted on wood placque.   2",
    "price": 349.0,
    "product_page": "product-detail.html?id=HEA-0001",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0002",
    "type": "autograph",
    "category": "model",
    "category2": "",
    "name": "Ivana Trump",
    "description": "Signed Card",
    "price": 59.99,
    "product_page": "product-detail.html?id=HEA-0002",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0003",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "George P. Shultz",
    "description": "8x10 Black & White Photograph.   Signed on the bottom.",
    "price": 29.99,
    "product_page": "product-detail.html?id=HEA-0003",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0004",
    "type": "autograph",
    "category": "comedy",
    "category2": "actor",
    "name": "Buddy Hackett",
    "description": "Signed Card",
    "price": 29.99,
    "product_page": "product-detail.html?id=HEA-0004",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0005",
    "type": "autograph",
    "category": "author",
    "category2": "politics",
    "name": "William F. Buckley Jr.",
    "description": "Signed \"Cordiallt\" 5x7 B&W Photo",
    "price": 0.0,
    "product_page": "product-detail.html?id=HEA-0005",
    "status": "",
    "quantity_available": 0
  },
  {
    "product_id": "HEA-0006",
    "type": "autograph",
    "category": "model",
    "category2": "",
    "name": "Chreyl Tiegs",
    "description": "Signed 3x5 index card.",
    "price": 34.99,
    "product_page": "product-detail.html?id=HEA-0006",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0007",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Warren Beatty",
    "description": "Signed  4x6 card.",
    "price": 45.0,
    "product_page": "product-detail.html?id=HEA-0007",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0008",
    "type": "autograph",
    "category": "vintage",
    "category2": "actress",
    "name": "Lauren Bacall",
    "description": "signed 3x5 index card.",
    "price": 40.0,
    "product_page": "product-detail.html?id=HEA-0008",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0009",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Fats Domino",
    "description": "signed 3x5 index card.",
    "price": 79.99,
    "product_page": "product-detail.html?id=HEA-0009",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0010",
    "type": "autograph",
    "category": "tv",
    "category2": "vintage",
    "name": "Pat Sajak",
    "description": "Signed 8x10 B&W photograph.",
    "price": 59.99,
    "product_page": "product-detail.html?id=HEA-0010",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0011",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "C. Everett Koop",
    "description": "Signed 8 x 10 Photo - inscribed.",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEA-0011",
    "status": "",
    "quantity_available": 1
  }
];
