const inventory = [
  {
    "product_id": "HEA-0001",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Shaquille O'Neal",
    "description": "Color 8x10 Of Shaq mounted on wood placque.   2",
    "price": 349.0,
    "product_page": "product-detail.html?id=HEA-0001",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0002",
    "type": "autograph",
    "category": "model",
    "category2": "",
    "name": "Ivana Trump",
    "description": "Signed Card",
    "price": 59.99,
    "product_page": "product-detail.html?id=HEA-0002",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0003",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "George P. Shultz",
    "description": "8x10 Black & White Photograph.   Signed on the bottom.",
    "price": 29.99,
    "product_page": "product-detail.html?id=HEA-0003",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0004",
    "type": "autograph",
    "category": "comedy",
    "category2": "actor",
    "name": "Buddy Hackett",
    "description": "Signed Card",
    "price": 29.99,
    "product_page": "product-detail.html?id=HEA-0004",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0005",
    "type": "autograph",
    "category": "author",
    "category2": "politics",
    "name": "William F. Buckley Jr.",
    "description": "Signed \"Cordiallt\" 5x7 B&W Photo",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0005",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0006",
    "type": "autograph",
    "category": "model",
    "category2": "",
    "name": "Chreyl Tiegs",
    "description": "Signed 3x5 index card.",
    "price": 34.99,
    "product_page": "product-detail.html?id=HEA-0006",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0007",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Warren Beatty",
    "description": "Signed  4x6 card.",
    "price": 45.0,
    "product_page": "product-detail.html?id=HEA-0007",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0008",
    "type": "autograph",
    "category": "vintage",
    "category2": "actress",
    "name": "Lauren Bacall",
    "description": "signed 3x5 index card.",
    "price": 40.0,
    "product_page": "product-detail.html?id=HEA-0008",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0009",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Fats Domino",
    "description": "signed 3x5 index card.",
    "price": 79.99,
    "product_page": "product-detail.html?id=HEA-0009",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0010",
    "type": "autograph",
    "category": "tv",
    "category2": "vintage",
    "name": "Pat Sajak",
    "description": "Signed 8x10 B&W photograph.",
    "price": 59.99,
    "product_page": "product-detail.html?id=HEA-0010",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0011",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "C. Everett Koop",
    "description": "Signed 8 x 10 Photo - inscribed.",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEA-0011",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0012",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Magic Johnson",
    "description": "Great signed color 8xa0 action shot",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0012",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0013",
    "type": "autograph",
    "category": "tv",
    "category2": "actor",
    "name": "Honeymooners - Signed by 3 - Carney, Meadows, Randolph",
    "description": "Nice 8x10 B&W 8x10 photo signed by 3 of Honeymooners",
    "price": 325.0,
    "product_page": "product-detail.html?id=HEA-0013",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0014",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Chet Atkins",
    "description": "Signed 3x5 index card.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0014",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0015",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Michael Bolton",
    "description": "Signed 4x6 index card.  Not inscribed.",
    "price": 45.0,
    "product_page": "product-detail.html?id=HEA-0015",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0016",
    "type": "autograph",
    "category": "music",
    "category2": "actress",
    "name": "Rosemary Clooney",
    "description": "Signed inscribed 8x10 B&W publicity photo.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0016",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0017",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Perry Como",
    "description": "Signed 3x5 index card.   Added \"Best Wishes\".",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0017",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0018",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Ray Conniff",
    "description": "Signed 4x5 B&W photo.    Added \"Best Wishes\".",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0018",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0019",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Lita Ford",
    "description": "Signed 8.5x11 B. C. Rick Guitars ad.  Inscribed & \"Keep Rockin\"",
    "price": 175.0,
    "product_page": "product-detail.html?id=HEA-0019",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0020",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Crystal Gayle",
    "description": "Signed 3.5x2.5 color trading card.  Inscribed to Mike.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0020",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0021",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Mickey Gilley",
    "description": "Signed 3x5 indx card,  (Not inscribed)",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0021",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0022",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Evonne Goolagong",
    "description": "Signed 3.5x2 card.  Inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0022",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0023",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Any Grant",
    "description": "Signed 3x5 index card.  Added \"God Bless You\"",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0023",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0024",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Marvin Hamlisch",
    "description": "Signed 3x5 index card.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0024",
    "status": "",
    "quantity_available": 1
  },
  {
    "product_id": "HEA-0025",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Al Hirt",
    "description": "Signed 3x5 indexcard.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0025",
    "status": "",
    "quantity_available": 1
  }
];
