const inventory = [
  {
    "product_id": "HEA-0001",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Shaquille O'Neal",
    "description": "Color 8x10 Of Shaq mounted on wood plaque.",
    "price": 199.0,
    "product_page": "product-detail.html?id=HEA-0001",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "plaque",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0002",
    "type": "autograph",
    "category": "model",
    "category2": "",
    "name": "Ivana Trump",
    "description": "Signed Card",
    "price": 59.99,
    "product_page": "product-detail.html?id=HEA-0002",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0003",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "George P. Shultz",
    "description": "8x10 Black & White Photograph.   Signed on the bottom.",
    "price": 29.99,
    "product_page": "product-detail.html?id=HEA-0003",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0004",
    "type": "autograph",
    "category": "comedy",
    "category2": "actor",
    "name": "Buddy Hackett",
    "description": "Signed Card",
    "price": 29.99,
    "product_page": "product-detail.html?id=HEA-0004",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0005",
    "type": "autograph",
    "category": "author",
    "category2": "politics",
    "name": "William F. Buckley Jr.",
    "description": "Signed \"Cordially\" 5x7 B&W Photo",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0005",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0006",
    "type": "autograph",
    "category": "model",
    "category2": "",
    "name": "Cheryl Tiegs",
    "description": "Signed 3x5 index card.",
    "price": 34.99,
    "product_page": "product-detail.html?id=HEA-0006",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0007",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Warren Beatty",
    "description": "Signed  4x6 card.",
    "price": 45.0,
    "product_page": "product-detail.html?id=HEA-0007",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0008",
    "type": "autograph",
    "category": "vintage",
    "category2": "actress",
    "name": "Lauren Bacall",
    "description": "signed 3x5 index card.",
    "price": 40.0,
    "product_page": "product-detail.html?id=HEA-0008",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0009",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Fats Domino",
    "description": "signed 3x5 index card.",
    "price": 79.99,
    "product_page": "product-detail.html?id=HEA-0009",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0010",
    "type": "autograph",
    "category": "tv",
    "category2": "vintage",
    "name": "Pat Sajak",
    "description": "Signed 8x10 B&W photograph.",
    "price": 59.99,
    "product_page": "product-detail.html?id=HEA-0010",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0011",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "C. Everett Koop",
    "description": "Signed 8 x 10 Photo - inscribed.",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEA-0011",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0012",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Magic Johnson",
    "description": "Great signed color 8x10 action shot.   Mounted on wooden plaque",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0012",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "plaque",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0013",
    "type": "autograph",
    "category": "tv",
    "category2": "actor",
    "name": "Honeymooners - Signed by 3 - Carney, Meadows, Randolph",
    "description": "Nice 8x10 B&W 8x10 photo signed by 3 of Honeymooners",
    "price": 325.0,
    "product_page": "product-detail.html?id=HEA-0013",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0014",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Chet Atkins",
    "description": "Signed 3x5 index card.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0014",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0015",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Michael Bolton",
    "description": "Signed 4x6 index card.  Not inscribed.",
    "price": 45.0,
    "product_page": "product-detail.html?id=HEA-0015",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0016",
    "type": "autograph",
    "category": "music",
    "category2": "actress",
    "name": "Rosemary Clooney",
    "description": "Signed inscribed 8x10 B&W publicity photo.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0016",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0017",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Perry Como",
    "description": "Signed 3x5 index card.   Added \"Best Wishes\".",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0017",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0018",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Ray Conniff",
    "description": "Signed 4x5 B&W photo.    Added \"Best Wishes\".",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0018",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0019",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Lita Ford",
    "description": "Signed 8.5x11 B. C. Rick Guitars ad.  Inscribed & \"Keep Rockin\"",
    "price": 175.0,
    "product_page": "product-detail.html?id=HEA-0019",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0020",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Crystal Gayle",
    "description": "Signed 3.5x2.5 color trading card.  Inscribed to Mike.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0020",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0021",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Mickey Gilley",
    "description": "Signed 3x5 indx card,  (Not inscribed)",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0021",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0022",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Evonne Goolagong",
    "description": "Signed 3.5x2 on her personal business card.  Inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0022",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0023",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Any Grant",
    "description": "Signed 3x5 index card.  Added \"God Bless You\"",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0023",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0024",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Marvin Hamlisch",
    "description": "Signed 3x5 index card.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0024",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0025",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Al Hirt",
    "description": "Signed 3x5 indexcard.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0025",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0027",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Eddie Albert",
    "description": "Signed inscribed 5x8 B&W photo,",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0027",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0028",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Tom Bosley",
    "description": "Signed 3x5 blue index card.   Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0028",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0029",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Ricou Browning",
    "description": "Signed 3x5 index card.  Not incribed.  Comes with 8x10 color photo of The Creature.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0029",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0030",
    "type": "autograph",
    "category": "actor",
    "category2": "comedy",
    "name": "Red Buttons",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0030",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0031",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Susan Clark",
    "description": "Signed 8x10 B&W photograph.   Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0031",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0032",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Jackie Cooper",
    "description": "Signed 8x10 B&W photograph.  Not inscribed.",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0032",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0033",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Kevin Costner",
    "description": "Signed 8x10 action photo from Robin Hood: Prince of Thieves - Not inscribed.",
    "price": 250.0,
    "product_page": "product-detail.html?id=HEA-0033",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0034",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Tony Danza",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 95.0,
    "product_page": "product-detail.html?id=HEA-0034",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0035",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Clint Eastwood",
    "description": "Signed 7x7 B&W photo from  A Perfect World.  Not inscribed.",
    "price": 375.0,
    "product_page": "product-detail.html?id=HEA-0035",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0036",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Buddy Ebsen",
    "description": "Signed 8x10 B&W photo from Barnaby Jones.  Not inscribed.",
    "price": 260.0,
    "product_page": "product-detail.html?id=HEA-0036",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0037",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Shaquille O'Neal",
    "description": "Signed color 8x10 action basketball jump shot.   Not inscribed.",
    "price": 175.0,
    "product_page": "product-detail.html?id=HEA-0037",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0038",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Patricia Neal",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0038",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0039",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Joe Pesci",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 259.0,
    "product_page": "product-detail.html?id=HEA-0039",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0040",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Walter Pidgeon",
    "description": "Signed cut card mounted on 3x5 index card.   Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0040",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0041",
    "type": "autograph",
    "category": "actress",
    "category2": "music",
    "name": "Juliet Prowse",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 65.0,
    "product_page": "product-detail.html?id=HEA-0041",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0042",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Vera Ralston",
    "description": "Signed 4x3.5 color polaroid    Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0042",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0043",
    "type": "autograph",
    "category": "actress",
    "category2": "comedy",
    "name": "Martha Raye",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 110.0,
    "product_page": "product-detail.html?id=HEA-0043",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0044",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Carl Reiner",
    "description": "Signed 8x10 B&W photograph.   Not inscribed.",
    "price": 160.0,
    "product_page": "product-detail.html?id=HEA-0044",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0045",
    "type": "autograph",
    "category": "actor",
    "category2": "miscellaneous",
    "name": "Rob Reiner",
    "description": "Signed 8x10 B&W photograph.  Not inscribed.",
    "price": 160.0,
    "product_page": "product-detail.html?id=HEA-0045",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0046",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Theresa Russell",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 35.0,
    "product_page": "product-detail.html?id=HEA-0046",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0047",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Armin Shimmerman",
    "description": "Signed color 8x10 as Quark with cast of Deep Space Nine.  Not inscribed.",
    "price": 130.0,
    "product_page": "product-detail.html?id=HEA-0047",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0048",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Jean Simmons",
    "description": "Signed 8x10 B&W photo from Androcles and the Lion.  Not inscribed.",
    "price": 175.0,
    "product_page": "product-detail.html?id=HEA-0048",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0049",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Tuesday Weld",
    "description": "Signed 4x6 card,  Not inscribed.",
    "price": 95.0,
    "product_page": "product-detail.html?id=HEA-0049",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0050",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Efrem Zimbalist Jr.",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0050",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0051",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Markie Post",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0051",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0052",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Dolph Lundgren",
    "description": "Signed 3x5 index card.  Not inscribed.   Comes with color 8x10 photo.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0052",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0053",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Sophia Loren",
    "description": "Signed 3x5 index card.  Not inscribed.  Comes with beautiful color 8x10 photo.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0053",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0054",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Angie Dickinson",
    "description": "Signed 3x5 index card.  Not inscribed.  Comes with color 8x10 photo of Dickinson.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0054",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0055",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "James Garner",
    "description": "Signed 3x5 index card.  Not inscribed.   Comes with a color 8x10 of James Garner.",
    "price": 180.0,
    "product_page": "product-detail.html?id=HEA-0055",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0056",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Connie Selleca",
    "description": "Signed 3x5 index card.  Not inscribed.   Comes with beautiful 8x10 photo of Selleca.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0056",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0057",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Edward G. Robinson",
    "description": "Right half of signed bank check.",
    "price": 225.0,
    "product_page": "product-detail.html?id=HEA-0057",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0058",
    "type": "autograph",
    "category": "miscellaneous",
    "category2": "",
    "name": "Richard Lester - Comes with A Hard Day's Night Poster",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0058",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0059",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Neil Young",
    "description": "Sined 3x5 index card.  Not inscribed.",
    "price": 300.0,
    "product_page": "product-detail.html?id=HEA-0059",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0060",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Aldo Ray and Jeff Donnell",
    "description": "Aldo Ray and Jeff Donnell double-signed index card",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0060",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0061",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Lloyd Bridges",
    "description": "Signed 8x10 B&W photo as Adm. Tug Benson from \"Hot Shots\".    Inscribed.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0061",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0062",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Donna Douglas",
    "description": "Signed B&W prono card as Elly May Clampett.   Inscribed",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0062",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0063",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Florence Henderson",
    "description": "Signed 4x5 B&W Brady Bunch photo.  Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0063",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0064",
    "type": "autograph",
    "category": "",
    "category2": "",
    "name": "Esther Williams",
    "description": "Signed 3x5 index card.  Not inscribed.   Comes with 8x10 B&W photo of Esther Williams.",
    "price": 110.0,
    "product_page": "product-detail.html?id=HEA-0064",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0065",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Holly Hunter",
    "description": "Signed  4x6 index card.  Not inscribed.  Comes with  8x10 color photo of Holly",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0065",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0066",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Charlton Heston",
    "description": "Signed B&W photo as Colonel George Taylor from Planet of the Apes",
    "price": 300.0,
    "product_page": "product-detail.html?id=HEA-0066",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEC-0001",
    "type": "collectible",
    "category": "memorabilia",
    "category2": "",
    "name": "Beatles Albums Coaster Set",
    "description": "Set of four -  3.75 x 3.75 inch glass Beatles album coasters.",
    "price": 35.0,
    "product_page": "product-detail.html?id=HEC-0001",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.95
  },
  {
    "product_id": "HEA-0067",
    "type": "autograph",
    "category": "music",
    "category2": "actor",
    "name": "Davy Jones",
    "description": "Signed CD cover.   Not inscribed.",
    "price": 175.0,
    "product_page": "product-detail.html?id=HEA-0067",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0068",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Phil Everly",
    "description": "Signed guitar strings package.   Not inscribed.",
    "price": 225.0,
    "product_page": "product-detail.html?id=HEA-0068",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0069",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "James Mercer - The Shins",
    "description": "Signed CD album insert from The Shins - Chutes Too Narrow",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0069",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0070",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Bea Arthur",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0070",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0071",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Rene Auberjonois",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0071",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0072",
    "type": "autograph",
    "category": "politics",
    "category2": "vintage",
    "name": "Elizabeth Dole",
    "description": "Signed 8x10 color photo.  Inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0072",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0074",
    "type": "autograph",
    "category": "",
    "category2": "",
    "name": "Jacqueline Bisset",
    "description": "Signed 4x6 index card.  Not inscribed.   Comes with color photo of Jacqueline",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0074",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0075",
    "type": "autograph",
    "category": "actress",
    "category2": "model",
    "name": "Erin Gray",
    "description": "Signed 8x10 B&W photo.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0075",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0076",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Kim Hunter",
    "description": "Signed 8x10 B&W photo.  Not inscribed.",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0076",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0077",
    "type": "autograph",
    "category": "actor",
    "category2": "actress",
    "name": "Steve Allen and Jayne Meadows",
    "description": "3x5 index cards signed by Steve Allen and Jayne Meadows w/Photo",
    "price": 215.0,
    "product_page": "product-detail.html?id=HEA-0077",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0078",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Maureen O'Sullivan",
    "description": "Signed 4.5 x 6 autograph album page.  Not inscribed.",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0078",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0079",
    "type": "autograph",
    "category": "actress",
    "category2": "model",
    "name": "Angel Tompkins",
    "description": "Signed 8x10 B&W photo.  Inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0079",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0080",
    "type": "autograph",
    "category": "actor",
    "category2": "miscellaneous",
    "name": "Peter Weller",
    "description": "Signed 3.5 x 2.5 inch Topps trading card from Robocop 2.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0080",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0081",
    "type": "autograph",
    "category": "actress",
    "category2": "comedy",
    "name": "Lily Tomlin",
    "description": "Signed 8x10 color photograph.  Inscribed.",
    "price": 95.0,
    "product_page": "product-detail.html?id=HEA-0081",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0082",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Jack Klugman",
    "description": "Signed 8x10 B&W photograph.  Inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0082",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0083",
    "type": "autograph",
    "category": "author",
    "category2": "comedy",
    "name": "Jim Davis",
    "description": "Signed Garfield 4.5 x 6 color Garfield and Odie card.   Not inscribed.",
    "price": 149.0,
    "product_page": "product-detail.html?id=HEA-0083",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0084",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "Gerald Ford",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0084",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0085",
    "type": "autograph",
    "category": "author",
    "category2": "",
    "name": "John Grisham",
    "description": "Signed 5x5 index card.  Not",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0085",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0086",
    "type": "autograph",
    "category": "author",
    "category2": "tv",
    "name": "Sidney Sheldon",
    "description": "Signed 5x2.75 cut paper.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0086",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0087",
    "type": "autograph",
    "category": "historical",
    "category2": "politics",
    "name": "William Westmoreland",
    "description": "Signed 8x10 color photograph.  Not inscribed.",
    "price": 240.0,
    "product_page": "product-detail.html?id=HEA-0087",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0088",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Danny Aiello",
    "description": "Signed B&W 8x10 photo.   Inscribed.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0088",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0089",
    "type": "autograph",
    "category": "actress",
    "category2": "music",
    "name": "Vivian Blaine",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0089",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0090",
    "type": "autograph",
    "category": "actor",
    "category2": "author",
    "name": "Bruce Boxleitner",
    "description": "Signed 8x10 B&W photo.   Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0090",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0091",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Adrian Booth Brian",
    "description": "Signed 3.5x5 B&W photo.   Not inscribed.",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0091",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0092",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Blair Brown",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0092",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0093",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Gary Busey",
    "description": "Signed 3x5 index card.  Not inscribed.  Comes with 8x10 color photo.",
    "price": 145.0,
    "product_page": "product-detail.html?id=HEA-0093",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0094",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Harry Carey Jr.",
    "description": "Signed 3x5 index card.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0094",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0095",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Rebecca DeMornay",
    "description": "Signed 8x10 color photograph.  Not inscribed.",
    "price": 200.0,
    "product_page": "product-detail.html?id=HEA-0095",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0096",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Faye Dunaway - Bonnie and Clyde",
    "description": "Signed 4x6 index card.  Not inscribed.",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0096",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0097",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Jack Elam",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0097",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0098",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Douglas Fairbanks Jr.",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0098",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0099",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Jamie Farr",
    "description": "Signed 8x10 B&W photo.  Not inscribed,",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0099",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0100",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Teri Garr",
    "description": "Signed 8x10 B&W photograph.  Inscribed.",
    "price": 135.0,
    "product_page": "product-detail.html?id=HEA-0100",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEC-0002",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "The American Breed",
    "description": "Album: Pumpkin, Powder, Scarlet & Green",
    "price": 20.0,
    "product_page": "product-detail.html?id=HEC-0002",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0003",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "The Moonglows",
    "description": "Album: The Return of the Moonglows",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEC-0003",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0004",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Five Brothers - Album:  Five Brothers (Jazz group)",
    "description": "Herbie Harper, Frank Capp, Red Mitchell, Bob Enevoldsen, Don Overburg",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEC-0004",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0005",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Cactus Flower  - Album:  Original Soundtrack",
    "description": "Vinyl LP.   Instrumental by Quincy Jones.   Vocal by Sarah Vaughan",
    "price": 40.0,
    "product_page": "product-detail.html?id=HEC-0005",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0006",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Lester Lanin - Album -  Christmas Dance party",
    "description": "Vinyl LP",
    "price": 10.0,
    "product_page": "product-detail.html?id=HEC-0006",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0007",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Bettye Swann - Album: Don't You Ever get tired of Hurting Me?",
    "description": "Vinyl record album.  10 tracks.  - Soul genre",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEC-0007",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0008",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Leslie Phillips - Album: Recollection",
    "description": "Vinyl LP.  13 tracks.",
    "price": 10.0,
    "product_page": "product-detail.html?id=HEC-0008",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0009",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "The Manzanilla Sound - Album",
    "description": "Vinyl Album.  11 Tracks",
    "price": 20.0,
    "product_page": "product-detail.html?id=HEC-0009",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0010",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Hollyridge Strings - Album: Christmas Favorites",
    "description": "Vinyl LP. 11 Tracks",
    "price": 25.0,
    "product_page": "product-detail.html?id=HEC-0010",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0011",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "The Sandpipers - Album: Come Saturday Morning",
    "description": "Vinyl LP.  9 Tracks",
    "price": 10.0,
    "product_page": "product-detail.html?id=HEC-0011",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEC-0012",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Terry Baxter Orchestra - Album: The Best of '69",
    "description": "Vinyl LP.  2-Record set.  25racks",
    "price": 15.0,
    "product_page": "product-detail.html?id=HEC-0012",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 12.99
  },
  {
    "product_id": "HEC-0013",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Leonard Bernstein.. Album: Rhapsody In Blue/American in Paris",
    "description": "Vinyl LP.",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEC-0013",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0014",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Dixie Echoes and Hal Kennedy.. Abum: Coming on Strong",
    "description": "Vinyl LP: 12 Tracks",
    "price": 10.0,
    "product_page": "product-detail.html?id=HEC-0014",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0015",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Bob & Carol & Ted & Alice.  Album: Movie Soundtrack",
    "description": "Vinyl LP: 10 Tracks",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEC-0015",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0016",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Dolenz, Jones, Boyce & Hart",
    "description": "Vinyl LP of same name.  12 tracks.",
    "price": 40.0,
    "product_page": "product-detail.html?id=HEC-0016",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0017",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Charlie - Album: Self-named",
    "description": "Vinyl LP: 9 tracks",
    "price": 20.0,
    "product_page": "product-detail.html?id=HEC-0017",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0018",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Frank Sinatra.  Album: The Voice.",
    "description": "Vinyl LP: 12 tracks.",
    "price": 20.0,
    "product_page": "product-detail.html?id=HEC-0018",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0019",
    "type": "collectible",
    "category": "records",
    "category2": "",
    "name": "Rolling Stones.  Album: Between The Buttons",
    "description": "Vinyl LP: 12 tracks",
    "price": 30.0,
    "product_page": "product-detail.html?id=HEC-0019",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEC-0020",
    "type": "collectible",
    "category": "memorabilia",
    "category2": "",
    "name": "Bop Hope - Gem Razor Blades ad",
    "description": "Saturday Evening Gem Razor Blades ad from 1937",
    "price": 25.0,
    "product_page": "product-detail.html?id=HEC-0020",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 10.99
  },
  {
    "product_id": "HEA-0101",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Sunny Tufts",
    "description": "Small signed 3.5x2 inch card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0101",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0102",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Al Stewart signed album. Inscribed.",
    "description": "Signed album: \"Year of the Cat\"",
    "price": 180.0,
    "product_page": "product-detail.html?id=HEA-0102",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0103",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Ginger Rogers",
    "description": "Signed B&W photograph. from the film \"The Major and the Minor\".   Not inscribed.",
    "price": 170.0,
    "product_page": "product-detail.html?id=HEA-0103",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "custom",
    "shipping_charge": 12.0
  },
  {
    "product_id": "HEA-0104",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Elizabeth Shue",
    "description": "Signed 3x5 Index card matted together with 8x10 color photograph.",
    "price": 145.0,
    "product_page": "product-detail.html?id=HEA-0104",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0105",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Fess Parker",
    "description": "Signed 2.5x5 card.  Not inscribed.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0105",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0106",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Art Carney",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0106",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0107",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Tony Randall",
    "description": "Signed 3x5 index card.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0107",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0108",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Joyce Randolph",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0108",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0109",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Debbie Reynolds",
    "description": "Sgned 3x5 card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0109",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0110",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "Jason Robards",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0110",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0111",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Ann Rutherford",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 95.0,
    "product_page": "product-detail.html?id=HEA-0111",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0112",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Emma Samms",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0112",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0113",
    "type": "autograph",
    "category": "sports",
    "category2": "vintage",
    "name": "Bo Schembechler",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0113",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0114",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "Pat Schroeder",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0114",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0115",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Robert Stack",
    "description": "Signed 3x5 paper.   Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0115",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0116",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Harry Dean Stanton",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0116",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0117",
    "type": "autograph",
    "category": "politics",
    "category2": "tv",
    "name": "George Stephanopoulos",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0117",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0118",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "Nicolas Cage",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 200.0,
    "product_page": "product-detail.html?id=HEA-0118",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0119",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Sally Struthers",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0119",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0120",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Shirley Temple",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 180.0,
    "product_page": "product-detail.html?id=HEA-0120",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0121",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Marlo Thomas",
    "description": "Signed 4x6 card.  Inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0121",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0122",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Bobby Vinton",
    "description": "Signed 4x6 card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0122",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0123",
    "type": "autograph",
    "category": "actor",
    "category2": "",
    "name": "James Caan",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 185.0,
    "product_page": "product-detail.html?id=HEA-0123",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0124",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Eli Wallach",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0124",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0125",
    "type": "autograph",
    "category": "tv",
    "category2": "actress",
    "name": "Vanna White",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0125",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0126",
    "type": "autograph",
    "category": "actress",
    "category2": "music",
    "name": "Anna Maria Alberghetti",
    "description": "Signed 3x5 card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0126",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0127",
    "type": "autograph",
    "category": "actress",
    "category2": "comedy",
    "name": "Ruth Buzzi",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0127",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0128",
    "type": "autograph",
    "category": "model",
    "category2": "actress",
    "name": "Kim Alexis",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0128",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0129",
    "type": "autograph",
    "category": "tv",
    "category2": "miscellaneous",
    "name": "Steve Allen",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0129",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0130",
    "type": "autograph",
    "category": "actress",
    "category2": "music",
    "name": "June Allyson",
    "description": "Signed 3x5 indes card.  Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0130",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0131",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Morey Amsterdam",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0131",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0132",
    "type": "autograph",
    "category": "actor",
    "category2": "miscellaneous",
    "name": "Lew Ayres",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 95.0,
    "product_page": "product-detail.html?id=HEA-0132",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0133",
    "type": "autograph",
    "category": "actress",
    "category2": "comedy",
    "name": "Madeline Kahn",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0133",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0135",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Ken Griffey Jr.",
    "description": "Signed color 8x10 mounted on wooden plaque.",
    "price": 200.0,
    "product_page": "product-detail.html?id=HEA-0135",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "plaque",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0136",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Dennis Rodman",
    "description": "Signed 8x10 color photo mounted on wooden plaque.",
    "price": 200.0,
    "product_page": "product-detail.html?id=HEA-0136",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "plaque",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0137",
    "type": "autograph",
    "category": "sports",
    "category2": "historical",
    "name": "Bill Essick (Vinegar Bill)",
    "description": "Signed hand-written 1948 letter on New York Yankees letterhead",
    "price": 275.0,
    "product_page": "product-detail.html?id=HEA-0137",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEC-0021",
    "type": "collectible",
    "category": "miscellaneous",
    "category2": "memorabilia",
    "name": "H. Roy Hamey",
    "description": "Typed letter from Hamey to William Frawley (Fred Mertz on I Love Lucy)",
    "price": 20.0,
    "product_page": "product-detail.html?id=HEC-0021",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0138",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Marlene Dietrich",
    "description": "Signed card - not inscribed.   Mounted with 8x10 B& Photo.  Framed.",
    "price": 185.0,
    "product_page": "product-detail.html?id=HEA-0138",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "framed",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0139",
    "type": "autograph",
    "category": "actor",
    "category2": "vintage",
    "name": "James \"Jimmy\" Stewart",
    "description": "Signed 11x14 B&W photo mounted in 17X13 frame.   Not Inscribed.",
    "price": 260.0,
    "product_page": "product-detail.html?id=HEA-0139",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "framed",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0140",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "George Foreman",
    "description": "Signed 3x5 Index Card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0140",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0141",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Don January",
    "description": "Signed 8x10 color photograph.  Not siscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0141",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0142",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Stefan Johannson",
    "description": "Signed 9x6 promo card.",
    "price": 25.0,
    "product_page": "product-detail.html?id=HEA-0142",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0143",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Nancy Kerrigan",
    "description": "Signed 4x6 index card.  Not inscribed.",
    "price": 1.0,
    "product_page": "product-detail.html?id=HEA-0143",
    "status": "",
    "quantity_available": 90,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0144",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Ray \"Boom Boom\" Mancini",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0144",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0145",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Floyd Patterson",
    "description": "Signed 8x10 B&W Photograph.   Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0145",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0146",
    "type": "autograph",
    "category": "",
    "category2": "",
    "name": "Roger Penske",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0146",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0147",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Kenny Perry",
    "description": "Signed 2.5x3.5 inch Pro Set sports card.   Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0147",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0148",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Ricky Rudd",
    "description": "signed 7x5 Color promo card.   Not inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0148",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0149",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Ken Schrader",
    "description": "Signed 3.5x2.5 Pro Set sports card.  Not Inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0149",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0150",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Dick Trickle",
    "description": "Signed 7x5 Color promo card.   Inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0150",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0151",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Johnny Vander Meer",
    "description": "Signed 3.5x2 inch card.  Not inscribed",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0151",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0152",
    "type": "autograph",
    "category": "comedy",
    "category2": "",
    "name": "Jerry Clower",
    "description": "Signed 3x5 index card.   Inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0152",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0153",
    "type": "autograph",
    "category": "tv",
    "category2": "music",
    "name": "Ralph Emery",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0153",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0154",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Barbra March",
    "description": "Signed 8x10 color photo as Klingon \"Lursa\".   Inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0154",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0155",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Morgan Shepherd",
    "description": "Signed  8x10 color promo card.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0155",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0156",
    "type": "autograph",
    "category": "actress",
    "category2": "music",
    "name": "Julie Brown and Charlie Coffey",
    "description": "Typed two-page contract signed by both Brown and Coffey.   Not inscribed.",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0156",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0157",
    "type": "autograph",
    "category": "actress",
    "category2": "author",
    "name": "Angela Cartwright.",
    "description": "Signed 4x6 B&W photo.  Inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0157",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0158",
    "type": "autograph",
    "category": "sports",
    "category2": "",
    "name": "Anfernee \"Penny\" Hardaway",
    "description": "Signed 8x10 color photograph.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0158",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0159",
    "type": "autograph",
    "category": "vintage",
    "category2": "miscellaneous",
    "name": "Ray Harryhausen",
    "description": "Signed 8x10 color photograph from 7th Voyage of Sinbad.   Not inscribed.",
    "price": 250.0,
    "product_page": "product-detail.html?id=HEA-0159",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0160",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Alan Young",
    "description": "Signed 8x10 B&W photo from The Time Machine.  Inscribed.",
    "price": 180.0,
    "product_page": "product-detail.html?id=HEA-0160",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0161",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Marty Balin - Jefferson Airplane",
    "description": "Signed art promo page - Not inscribed.",
    "price": 275.0,
    "product_page": "product-detail.html?id=HEA-0161",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0162",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Turtles - Mark Volman and Howard Kaylan",
    "description": "Signed on cut 4.5 x2.75 paper.     Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0162",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0163",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Joey Molland - Badfinger",
    "description": "Signed on back of 3.5x2 inch business card.   In-person. Inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0163",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0164",
    "type": "autograph",
    "category": "",
    "category2": "",
    "name": "Tom Reynolds - Hamilton, Joe Frank & Reynolds.  In-person.  Inscribed",
    "description": "Signed back of 3.5x2 inch business card.",
    "price": 40.0,
    "product_page": "product-detail.html?id=HEA-0164",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0165",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Peter Noone - Herman's Hermits",
    "description": "Cut 3x2.75 inch cut paper.  Inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0165",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0166",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Grass Roots - 4 members with bonus Gary Lewis",
    "description": "Signed 4.5x3 inch cut paper.   Not inscribed.",
    "price": 175.0,
    "product_page": "product-detail.html?id=HEA-0166",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0167",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Gary Lewis - Gary Lewis and the Playboys",
    "description": "Signed 9x4 back of flyer for rock venue.   Not inscribed",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0167",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0168",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Roger McGuinn - The Byrds",
    "description": "Signed 5.5x1.75 inch ticket sub.   Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0168",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0169",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Carl Perkins",
    "description": "Signed 7x9.5 inch paper.  Inscribed",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0169",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0170",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "John Sebastian - Lovin' Spoonful",
    "description": "Signed 8x10 color photograph.  Not inscribed.  In-person.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0170",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0171",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Neil Sedaka",
    "description": "Signed 8x10 B&W photograph.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0171",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0172",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Dennis Yost - Classics IV",
    "description": "Signed 4x2.5 inch card.  Not inscribed.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0172",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0173",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Maureen O'Hara",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0173",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0174",
    "type": "autograph",
    "category": "actress",
    "category2": "",
    "name": "Martha O'Driscoll",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0174",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0175",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Elizabeth McGovern",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0175",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0176",
    "type": "autograph",
    "category": "tv",
    "category2": "actor",
    "name": "Clayton Moore - The Lone Ranger",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0176",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0177",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Kathy Mattea",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0177",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0178",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Janet Leigh - Psycho",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0178",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0179",
    "type": "autograph",
    "category": "music",
    "category2": "",
    "name": "Brenda Lee - \u201cRockin\u2019 Around the Christmas Tree.\u201d",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0179",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0180",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Cheryl Ladd Charlie's Angels",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0180",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0181",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Walter Koenig - Chekhov - Star Trek",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0181",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0182",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Gloria Jean",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0182",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0183",
    "type": "autograph",
    "category": "music",
    "category2": "actor",
    "name": "Ferlin Husky",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0183",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0184",
    "type": "autograph",
    "category": "tv",
    "category2": "actress",
    "name": "Kathy Garver - Family Affair",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0184",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0185",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Mike Connors - Mannix",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0185",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0186",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Rita Gam",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0186",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0187",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Bonnie Franklin - One Day at a Time",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0187",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0188",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Tony Franciosa - A Hatful of Rain",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0188",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0189",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Nina Foch - Executive Suite",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0189",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0190",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Louise Fletcher - Nurse Ratched - One Flew Over The Cuckoo's Nest",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0190",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0191",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Pat Crowley - Please Don't Eat the Daisies",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0191",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0192",
    "type": "autograph",
    "category": "sports",
    "category2": "tv",
    "name": "Peggy Fleming - Gold Medal Olympics 1968",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0192",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0193",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Barbara Feldon - Agent 99 - Get Smart",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0193",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0194",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Jamie Farr - Corporal Klinger - M*A*S*H",
    "description": "Signed 3x5 index card.  Not inscribed",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0194",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0195",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Billie Dove - Blondie of the Follies",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 140.0,
    "product_page": "product-detail.html?id=HEA-0195",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0196",
    "type": "autograph",
    "category": "actor",
    "category2": "miscellaneous",
    "name": "Tom Cruise - Top Gun, Rain Man, Mission Impossible",
    "description": "Signed 4x6 index card.  Not inscribed.",
    "price": 350.0,
    "product_page": "product-detail.html?id=HEA-0196",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0197",
    "type": "autograph",
    "category": "comedy",
    "category2": "actress",
    "name": "Phyllis Diller",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0197",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0198",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Diane Baker - Silence of the Lambs",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0198",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0199",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Binnie Barnes - The Private Life of Henry VIII",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0199",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0200",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Valerie Bertinelli - One Day at a Time",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0200",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0201",
    "type": "autograph",
    "category": "politics",
    "category2": "historical",
    "name": "Julian Bond",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0201",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0202",
    "type": "autograph",
    "category": "music",
    "category2": "actor",
    "name": "Pat Boone - April Love",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 65.0,
    "product_page": "product-detail.html?id=HEA-0202",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0203",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Alice Faye - Alexander\u2019s Ragtime Band",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0203",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0204",
    "type": "autograph",
    "category": "author",
    "category2": "miscellaneous",
    "name": "Jackie Collins - Hollywood Wives",
    "description": "Signed 4x6 index card.  Inscribed",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0204",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0205",
    "type": "autograph",
    "category": "actress",
    "category2": "model",
    "name": "Angel Tompkins - I Love My Wife",
    "description": "Signed 5x2.75 inch cut paper.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0205",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0206",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Marjorie Lord - Make Room for Daddy",
    "description": "Signed 8x10 B&W photograph.   Inscribed.",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0206",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0207",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Chad and Jeremy",
    "description": "Signed Distant Shores framed vinyl LP.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0207",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "framed",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0208",
    "type": "autograph",
    "category": "music",
    "category2": "vintage",
    "name": "Donovan (Sunshine Superman, Mellow Yellow)",
    "description": "Signed Open Road framed vinyl LP.  No inscribed.  In-Person.",
    "price": 125.0,
    "product_page": "product-detail.html?id=HEA-0208",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "framed",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0209",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "John Larroquette - Night Court",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 75.0,
    "product_page": "product-detail.html?id=HEA-0209",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0210",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Vicki Lawrence - The Carol Burnett Show",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0210",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0211",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Gloria Loring - Days of Our Lives",
    "description": "Signed 3x5 index card.   Not inscribed.",
    "price": 60.0,
    "product_page": "product-detail.html?id=HEA-0211",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0212",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Deanna Lund - Land of the Giants",
    "description": "Signed 8.5x11 inch copy of TV Guide Magazine Cover.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0212",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0213",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Mary Ann Mobley",
    "description": "Signed 8x10 B&W photograph.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0213",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0214",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Ricardo Montalbon - Mr. Roarke on Fantasy Island",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0214",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0215",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Martin Mull - Fernwood 2 Night",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 85.0,
    "product_page": "product-detail.html?id=HEA-0215",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0216",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Leslie Neilson - The Naked Gun",
    "description": "Signed 3.5x5.5 inch color photograph.  Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0216",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0217",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Richard Paul - The People vs. Larry Flynt",
    "description": "Signed 8.5x11 promo page.  Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0217",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0218",
    "type": "autograph",
    "category": "actress",
    "category2": "vintage",
    "name": "Margaret Pellegrini - Munchkin in Wizard of Oz",
    "description": "Signed 3x5 index card.  Inscribed.",
    "price": 150.0,
    "product_page": "product-detail.html?id=HEA-0218",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0219",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Joyce Randolph - The Honeymooners",
    "description": "Signed 8x10 B&W photograph.  Inscribed.",
    "price": 100.0,
    "product_page": "product-detail.html?id=HEA-0219",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0220",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Connie Selleca - The Greatest American Hero",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 80.0,
    "product_page": "product-detail.html?id=HEA-0220",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0221",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Armin Shimerman - Deep Space Nine",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 50.0,
    "product_page": "product-detail.html?id=HEA-0221",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0222",
    "type": "autograph",
    "category": "actor",
    "category2": "miscellaneous",
    "name": "Wesley Snipes - Blade",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0222",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0223",
    "type": "autograph",
    "category": "actress",
    "category2": "model",
    "name": "Brinke Stevens",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 65.0,
    "product_page": "product-detail.html?id=HEA-0223",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0224",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "George Takei - Sulu in Star Trek",
    "description": "Signed 3.5x2.5 inch Star Trek trading card.  Not inscriibed.",
    "price": 170.0,
    "product_page": "product-detail.html?id=HEA-0224",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0225",
    "type": "autograph",
    "category": "actress",
    "category2": "miscellaneous",
    "name": "Lea Thompson - Back to the Future",
    "description": "Signed 4x6 B&W photograph.  Not inscribed.",
    "price": 90.0,
    "product_page": "product-detail.html?id=HEA-0225",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0226",
    "type": "autograph",
    "category": "model",
    "category2": "tv",
    "name": "Cheryl Tiegs",
    "description": "Signed 8x10 B&W photograph.  Not inscribed.",
    "price": 130.0,
    "product_page": "product-detail.html?id=HEA-0226",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0227",
    "type": "autograph",
    "category": "",
    "category2": "",
    "name": "Brenda Vaccaro - Midnight Cowboy",
    "description": "Signe 8x8 photograph promo card.   Not inscribed",
    "price": 95.0,
    "product_page": "product-detail.html?id=HEA-0227",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0228",
    "type": "autograph",
    "category": "actress",
    "category2": "tv",
    "name": "Vanna White - Wheel of Fortune",
    "description": "Gorgeous signed 8x10 B&W photograph.  Not inscribed.",
    "price": 120.0,
    "product_page": "product-detail.html?id=HEA-0228",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  },
  {
    "product_id": "HEA-0229",
    "type": "autograph",
    "category": "actor",
    "category2": "tv",
    "name": "Peter Marshall - Hollywood Squares",
    "description": "Signed 3x5 index card.  Not inscribed.",
    "price": 70.0,
    "product_page": "product-detail.html?id=HEA-0229",
    "status": "",
    "quantity_available": 1,
    "shipping_class": "standard",
    "shipping_charge": ""
  }
];
